// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDDeZqKCZf7APjovPx7MUv-orp7iyfEsxs',
    appId: '1:1057912974725:android:d2c5dcf9c514a78b1c28ec',
    messagingSenderId: '1057912974725',
    projectId: 'let-s-walk-gdsc-dd902',
    storageBucket: 'let-s-walk-gdsc-dd902.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBNvLrMwTrt6xwoIOKeiVAes0TgqapwlgQ',
    appId: '1:1057912974725:ios:6c5ff1b4b3d6918f1c28ec',
    messagingSenderId: '1057912974725',
    projectId: 'let-s-walk-gdsc-dd902',
    storageBucket: 'let-s-walk-gdsc-dd902.appspot.com',
    iosClientId: '1057912974725-ga549964c05p15agf4h1020mqg5322eo.apps.googleusercontent.com',
    iosBundleId: 'com.ping',
  );
}
